### ISSUE TITLE
Meet Problem when boot the machine with QEMU.

### ISSUE THREAD

**Issue by melonpass** [keystone-enclave/keystone#168]
I used the docker image, and make run-tests command worked fine. 
But when I use run-qemu.sh,  I'm stuck at login prompt. It need a passwd.
I just don't know where to find the password or how to set it myself.

**Comment by dayeol** [comment]
Sorry, we missed the login information in the docs for docker image.
Login as `root` with the password `sifive`.

You can also change the password by changing `BR2_TARGET_GENERIC_ROOT_PASSWD` in
`conf/qemu_riscv64_virt_defconfig`
and then rebuilding the buildroot.

We haven't updated the docker image since 0.3, so probably you should refer to 0.3 docs unless you update the github repo inside the docker image.

**Comment by dayeol** [comment]
OK, for v0.3, the config file is actually
`hifive-conf/buildroot_initramfs_config`

**Comment by dayeol** [comment]
Closing
