### ISSUE TITLE
How to do the deep learning calculation in the keystone?

### ISSUE THREAD

**Issue by RMheng** [keystone-enclave/keystone#181]
Hi, 
I want to reproduce the resnet50 calculation in the keystone. But keystone is based on the RISC-V, which cannot just use opencv and libtorch like on the gcc environment. 

I read keystone paper, which describe 
> We ran nine Torch-based models of increasing sizes with Eyrie on the Imagenet dataset [58] (see Table 6). They comprise 15.7 and 15.4KLoC of TH [13] and THNN [16] libraries from Torch compiled with musl libc. Each model has an additional 230 to 13.4KLoC of model-specific inference code.

I’m confused that in the keystone how to do the inference. Is there any pytorch API for the RISC-V environment? Thanks for your reading and looking forward to your reply！

**Comment by dkohlbre** [comment]
Hi,
I'll answer this here, but in general please take non-bug/feature questions to our mailing list: https://groups.google.com/forum/#!forum/keystone-enclave-forum
I'll close this bug and we can continue discussion on the mailing list if you've got followup questions.

I think there is some confusion about RISC-V and the libraries we used in the paper.

GCC (the compiler toolchain) can absolutely compile to RISC-V, rather than targeting x86 or ARM. We used a musl-gcc build cross-compiling to RISC-V to build the binaries we used in our tests. 
(see: https://wiki.musl-libc.org/getting-started.html#Building-a-cross-compiler-targeting-musl-libc or use the rv8-musl toolchain https://github.com/rv8-io/musl-riscv-toolchain) Building an application cross-compiled to RISC-V and using torch (not pytorch) libraries is entirely possible.

As for pytorch, we've not worked on getting a running python interpreter into an enclave. Again, should be possible but it will be significantly more work.

Unfortunately we can't release the exact builds we used, as they come from another project's work (https://arxiv.org/pdf/1810.00602.pdf)
