### ISSUE TITLE
How to deploy keystone on BOOM

### ISSUE THREAD

**Issue by hz1490919302** [keystone-enclave/keystone#199]
I am a  student. I try to deploy keystone on BOOM, and then test the Spectre attack. What should I do, do I need to use FireSim or a real development board?

**Comment by dayeol** [comment]
Keystone is currently not fully integrated into Chipyard, but you can follow [this document](http://docs.keystone-enclave.org/en/latest/Getting-Started/Running-Keystone-with-FireSim.html) to try. 
Please change the deployment config to use BOOM instead of Rocket.
Let me know if you have any questions while you're trying the document.

**Comment by dayeol** [comment]
Integrating Keystone with Chipyard will make this much easier 
https://github.com/keystone-enclave/keystone/issues/200

**Comment by dayeol** [comment]
This should be resolved by #208. You can follow the FireSim document to configure your RTL with BOOM, and then build Keystone software stack with FireMarshal.
