### ISSUE TITLE
A random SSH port generated for each build

### ISSUE THREAD

**Issue by jarkkojs** [keystone-enclave/keystone#347]
A random SSH port is generated in the `CMakeLists.txt`. Is there a good reason for this because a variable port number decreases portability.

**Comment by dkohlbre** [comment]
The port (should) only be used for the localhost qemu instance, it doesn't affect anything about the built image/etc.
Can you give a concrete example for where this would hurt portability?

We do this because when you have a bunch of people sharing build infrastructure and testing using the same ssh port for all qemu instances won't work.

**Comment by jarkkojs** [comment]
Hmm... But... They have different IPs, right? Maybe this should be clarified in `README.md`.

**Comment by dkohlbre** [comment]
Unless you are making that ssh port outbound, its only going to be on the localhost interface.
So, by default, this is only accessible to users already on that machine.

In our case, many of us share a build and test machine, so we can't _all_ be using localhost:SOMEPORT at the same time :)

**Comment by jarkkojs** [comment]
ok cool, thanks for explanation :-) i will close this now.
