### ISSUE TITLE
Passing parameters to the SM from the bootROM

### ISSUE THREAD

**Issue by CarusoGiuseppe** [keystone-enclave/keystone#411]
Hi, after passing some parameters declared as extern in sm.c and compiling, i'm receiving the undefined reference error whenever the parameter were added to the sanctum_params.ldS file. Even after adding correctly the parameters and managing them as the sanctum parameters already present, i still can't find a way to solve this issue and to use such parameters in the SM. So i was wandering if there is something more that i should do to pass the params from bootROM to SM.

**Comment by grg-haas** [comment]
Hi @CarusoGiuseppe . From my understanding of what you're trying to do, I believe you'll also need to patch OpenSBI's linker script very similarly as to what we do [here](https://github.com/keystone-enclave/keystone/blob/master/overlays/keystone/patches/opensbi/opensbi-firmware-secure-boot.patch). This will allow the bootrom to communicate information with the SMl. After adding your patch file in this directory, you'll want to do:

```
BUILDROOT_TARGET=opensbi-dirclean make
```

for your platform, followed by running your build again so that the patch file in included.

**Comment by CarusoGiuseppe** [comment]
Hi @grg-haas ! Thanks for the answer! So do i need to add a file that i should include somewhere or can i just modify the patch file ? Also, so i just need to add the patch file, call the dirclean and then the make command to build ?

**Comment by CarusoGiuseppe** [comment]
@grg-haas i've solved the issue, thank you so much!

**Comment by wcsjdzz** [comment]
hi, sorry to bother you, but i have met the same error, how di you solve it? thank you!
