### ISSUE TITLE
Guidance on adding a new SBI call

### ISSUE THREAD

**Issue by niovi** [keystone-enclave/keystone#435]
Hello ,

I am relatively new to Keystone and am currently exploring the process of adding a new SBI call. I'm trying to repeat the steps described in the get_sealing_key flow to create my own SBI call. However, despite my efforts, I seem to be missing something.

Could someone point me in the direction of documentation or provide guidance on the necessary steps and changes that need to be made when adding a new SBI call? 

Thank you in advance.

**Comment by dayeol** [comment]
Unfortunately, there's no documentation.

For adding an SBI, you should first decide if this is callable from the
host or from the enclave.
Add a call code to
https://github.com/keystone-enclave/keystone/blob/master/sdk/include/shared/sm_call.h
And then, add the case here
https://github.com/keystone-enclave/keystone/blob/master/sm/src/sm-sbi-opensbi.c

Please let me know if you have any questions.

**Comment by niovi** [comment]
Thank you very much for your prompt response.

I would like the SBI to be callable from the enclave.
I would like an SBI call function that returns a "hello world". So i create a new sdk example that host.ccp is like that 
![Screenshot from 2024-04-04 12-40-36](https://github.com/keystone-enclave/keystone/assets/23433382/abfb7e8c-24f9-4b95-bd43-4bd0c64abf4a)
 and a test.c in eap that i call the function get_hello();
I added a call code :
#define SBI_SM_GET_HELLO         3007
and the case in sm-sbi-opensbi.c:
case SBI_SM_GET_HELLO:
      retval =sbi_sm_get_hello(regs->a0, regs->a1);

also sbi_sm_get_hello() function in sm-sbi.c.

If my approach seems entirely off base and I may be attempting something that lacks coherence or practicality, I would greatly appreciate any advice or guidance on how to proceed.

**Comment by grg-haas** [comment]
Hi @niovi! This all looks correct so far. One thing you will also need is a definition of a *runtime* syscall which will end up calling the SBI call (since the eapp, running in U mode, cannot directly invoke the SM which is running in M mode). To do so, you'll need another definition for `RUNTIME_SYSCALL_GET_HELLO` in `sdk/include/shared/eyrie_call.h`, a corresponding syscall definition (in `sdk/src/app/syscall.c`) that looks like:

```(C)
void get_hello() {
  return SYSCALL_0(RUNTIME_SYSCALL_GET_HELLO);
}
````

You also need an *implementation* of that syscall in the runtime. To `runtime/call/syscall.c`, add another `case` in the `handle_syscall` function:

```(C)
...
case(RUNTIME_SYSCALL_GET_HELLO):
    sbi_get_hello();
    break;
```

And finally, this function in `runtime/call/sbi.c`:

```(C)
void
sbi_get_hello() {
  SBI_CALL_0(SBI_EXT_EXPERIMENTAL_KEYSTONE_ENCLAVE, SBI_SM_GET_HELLO);
}

```

**Comment by niovi** [comment]
Thank you very much for your answer; it really helped me.

Regarding the SYSCALL_0 and SBI_CALL_0 option, I would like to ask about the difference compared to the other SYSCALL, SBI. For example, if I want to return a buffer, should I use SYSCALL_1, SBI_CALL_1?

Can you explain how this mechanism works?

Thank you in advance.

**Comment by grg-haas** [comment]
Yeah for sure! The `SYSCALL_X` and `SBI_CALL_X` macros take `X` arguments respectively, to pass down to either the runtime  or the SM respectively. So `SYSCALL_1` passes one argument to the runtime (i.e. a function like `void get_hello(uint64_t arg0)`), and same thing for `SBI_CALL_X`.

I'm unsure if *returning* a buffer is currently possible. However, what is possible is *filling* a buffer with data from the SM. Assuming you want your data to end up in the eapp, you could define a syscall with `SYSCALL_2` and create a function like:

```(C)
int fill_buffer(void *buf, size_t sz) {
    return SYSCALL_2(RUNTIME_SYSCALL_FILL_BUFFER, but, sz);
}
```

You may need to cast the arguments to `uint64_t`.  Now, keep in mind that `but` here is a *userspace virtual address*, which the SM does not understand. Therefore, before passing `buf` down to the SM, you need to convert it to a *physical* address. The runtime provides a `translate` function for this. So, your syscall implementation in the runtime should look like:

```(C)
int
sbi_fill_buffer(void *buf, size_t sz) {
  SBI_CALL_2(SBI_EXT_EXPERIMENTAL_KEYSTONE_ENCLAVE, SBI_SM_FILL_BUFFER, translate(buf), sz);
}
```

Finally, in the SM syscall implementation, you can `memcpy` directly to the argument you receive since it is a physical address.

**Comment by niovi** [comment]
Thank you very much for all the help; I managed to make the SBI call. I would like to ask one final question to wrap up the issue. In case I want to deploy 2 enclaves, will they have the same SM? In other words, is there one SM per enclave, or one SM for all enclaves?

**Comment by grg-haas** [comment]
There is only one SM for all enclaves!
