### ISSUE TITLE
How SM works

### ISSUE THREAD

**Issue by alan2031** [keystone-enclave/keystone#450]
Hello, I have questions regarding the operation of the secure monitor in machine mode.

1.How can I ensure that the secure monitor runs in machine mode?
2.How can I determine which core's PMP registers are being modified in a multi-core system?

Thank you for your assistance!

**Comment by grg-haas** [comment]
Hi @alan2031!

1. I'm not sure if RISC-V has an architecture-defined way to get the current execution mode. Suffice it to say that the CPUs we support start up in m-mode, and since the SM is the first loaded firmware, it will be executing in m-mode as well. However, if you want to double-check, you could try reading from one of the m-mode-only CSRs. Maybe `mstatus` or `mepc`? This would only work in m-mode.
2. It is always the "current" core's PMP registers that are modified. That is, if the SM running on CPU3 changes a value in `pmpaddr*` or `pmpcfg*`, it is only *that* CPU's PMP configuration that is changed -- all other CPUs will not update in the same way. I believe the SM uses inter-processor interrupts to deliver notifications of PMP changes to all CPUs in the system.

**Comment by alan2031** [comment]
> Hi @alan2031!
> 
> 1. I'm not sure if RISC-V has an architecture-defined way to get the current execution mode. Suffice it to say that the CPUs we support start up in m-mode, and since the SM is the first loaded firmware, it will be executing in m-mode as well. However, if you want to double-check, you could try reading from one of the m-mode-only CSRs. Maybe `mstatus` or `mepc`? This would only work in m-mode.
> 2. It is always the "current" core's PMP registers that are modified. That is, if the SM running on CPU3 changes a value in `pmpaddr*` or `pmpcfg*`, it is only _that_ CPU's PMP configuration that is changed -- all other CPUs will not update in the same way. I believe the SM uses inter-processor interrupts to deliver notifications of PMP changes to all CPUs in the system.

Hi grg-haas!
Thank you very much for your help! I now understand the first point. Regarding the second point, for example, if I have a quad-core system, do they share the same secure monitor? If so, how can I choose which core it runs on? Thank you.

**Comment by grg-haas** [comment]
The SM runs on all of the CPUs in the system at the same time -- you can think of it as a multithreaded program, where each thread corresponds to a physical CPU core.

What specifically are you trying to do? Lets say you're running one of the keystone examples to create an enclave. When the host program calls down to Linux to set up an enclave, Linux will in turn call into the SM to configure its PMP registers. Whatever CPU happens to be running the userspace host program will also be the one that first sets its PMP configuraiton. However, that CPU  will then immediately IPI all the other CPUs to let them know to update their PMP configurations as well.

**Comment by alan2031** [comment]
> The SM runs on all of the CPUs in the system at the same time -- you can think of it as a multithreaded program, where each thread corresponds to a physical CPU core.
> 
> What specifically are you trying to do? Lets say you're running one of the keystone examples to create an enclave. When the host program calls down to Linux to set up an enclave, Linux will in turn call into the SM to configure its PMP registers. Whatever CPU happens to be running the userspace host program will also be the one that first sets its PMP configuraiton. However, that CPU will then immediately IPI all the other CPUs to let them know to update their PMP configurations as well.

As you mentioned, I want to use the Keystone example to create an enclave. Now I understand, thank you for your help！
